### ISSUE TITLE
Paired-end view screenshots now shown

### ISSUE THREAD

**Issue by ralonso-igenomix** [tobiasrausch/wally#1]
Dear,

Paired-end view screenshots now shown in main github section is not showing.

Best,

Roberto

**Comment by tobiasrausch** [comment]
Somehow the [placeholder, colored rectangles](https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file) are not working anymore with GitHub markdown. I will check why this is not working anymore.

**Comment by tobiasrausch** [comment]
I am sorry for the delay. This has been fixed now in the README.
