### ISSUE TITLE
-s option in matches

### ISSUE THREAD

**Issue by MJoseMo** [tobiasrausch/wally#11]
Hi, I have a question about  `-s` option of matches function. The help message of this function indicate that this option is for specifying the minimum size. However, the GitHub description suggests that this option creates different plots for each read of the file.

**Comment by tobiasrausch** [comment]
Thanks for noticing. That was a typo in the GitHub README. Fixed by commit 64a8fc400372ed258cb2d1c665ec29bdff87f7fc
