### ISSUE TITLE
Linked bioRxiv going to another manuscript

### ISSUE THREAD

**Issue by ralonso-igenomix** [tobiasrausch/wally#2]
Dear,

[bioRxiv 2022.02.20.480758](https://doi.org/10.1101/2022.02.20.480758)

Not going to wally manuscript.

Best,

Roberto

**Comment by tobiasrausch** [comment]
Dear Roberto,

We developed wally as one of the tools used in this study on bioRxiv. We do not have a separate method manuscript yet.

Best, Tobias

**Comment by tobiasrausch** [comment]
I have clarified this now in the README.
