### ISSUE TITLE
wally region

### ISSUE THREAD

**Issue by ylevmirom** [tobiasrausch/wally#3]
Hi Tobias, 

im trying to plot a simple example of mine, using this code: 
`/mnt/data/Tools/wally/src/wally region -R new_regions.bed  -g Wheat.Svevo.CHROMOSOMES.fasta G305sv2.sorted.bam `
im getting an error: 
```
[2022-Nov-03 14:38:56] wally region -R new_regions.bed -g Wheat.Svevo.CHROMOSOMES.fasta G305sv2.sorted.bam 
[E::sam_hrecs_update_hashes] Duplicate entry "Chr1A" in sam header
Invalid region Chr1A:1400289-1400389
Chromosome not found in BAM file.
```

I checked the chromosome names, seems to be OK. 
hope its clear, 

thanks, 

Yael

**Comment by tobiasrausch** [comment]
Looks like `Chr1A` is twice in the header. That's an error from HTSlib. Can you index the BAM file?

`samtools index G305sv2.sorted.bam`
