### ISSUE TITLE
support http & s3 protocole

### ISSUE THREAD

**Issue by dridk** [tobiasrausch/wally#5]
Hi,

Greate tool ! It would be awesome if you support http and s3 protocol . 
Htslib already supports this. It may be helpfull  :http://www.htslib.org/doc/htslib-s3-plugin.html  

```
wally region -r chr3:232-4234  s3://path/bucket/test.bam -g hg19.fa
```

**Comment by tobiasrausch** [comment]
Thanks! I also think such support for s3 would be very useful, but I have yet to see how easy it is to implement.

**Comment by tobiasrausch** [comment]
I am sorry for the very late reply. You can now access files via s3 or http(s) URLs with the latest code, e.g.:

`wally region -r chr17:7501000-7503000 -g hg38.fa https://ftp.sra.ebi.ac.uk/vol1/run/ERR398/ERR3988761/HG00405.final.cram`

`wally region -r chr17:7501000-7503000 -g hg38.fa s3://1000genomes-dragen-3.7.6/data/individuals/hg38-graph-based/HG00405/HG00405.bam`
