### ISSUE TITLE
Multiple bed for `wally region`

### ISSUE THREAD

**Issue by baozg** [tobiasrausch/wally#6]
Hi,

Is it possible to load multiple annotation resources (gene, repeat, histone markers etc. ) in the layer for `wally region` to infer the functional region?

**Comment by tobiasrausch** [comment]
Currently not but wally displays the label in the BED file (column 4) if there is sufficient space. So you can maybe merge the BED files with distinct (short) labels for each class?

**Comment by baozg** [comment]
I already tried labeling with the TE family. Did the RGB color in the bed will work?

**Comment by baozg** [comment]
Wow, super fast speed! Thanks for your development. Now I could hunt complex SVs with `wally` help. Happy holidays🎄!
