### ISSUE TITLE
Inconsistence with IGV

### ISSUE THREAD

**Issue by baozg** [tobiasrausch/wally#7]
Hi, 

`wally` speed is really impressive for a large bam. I am using it to visualize the whole genome alignment bam, so the contig could be chromosome-scale. But I found one region's display is inconsistence with IGV. I thought it was because the insert size cutoff, but I still couldn't go the same result even if I low / up down the `-m`. 

```bash

# Wally version: v0.5.8
# using Boost: v1.74.0
# using HTSlib: v1.17

wally region -g ref.fa -b gene.bed.gz -x 2048 -r Chrx:x-x align.sorted.bam
wally region -g ref.fa -b gene.bed.gz -x 2048 -m 0 -r Chrx:x-x align.sorted.bam
wally region -g ref.fa -b gene.bed.gz -x 2048 -m 100 -r Chrx:x-x align.sorted.bam
```

![Chr5_3178413_3185361](https://github.com/tobiasrausch/wally/assets/20680150/d55b8705-4b13-4a16-9e22-c507743d6ea0)
<img width="1327" alt="image" src="https://github.com/tobiasrausch/wally/assets/20680150/3e8900ed-47be-4d4e-a034-c8886f6a5a3f">

**Comment by tobiasrausch** [comment]
I am not sure what you mean by "inconsistent". Wally is not identical to IGV, SNVs and InDels are slightly differently visualized depending on the zoom level. The same is true for abnormal paired-ends and clipped reads. I currently don't see a bug or mistake in these screenshots.

**Comment by baozg** [comment]
I understand the small InDel and SNV may be different. But I am surprised that the large insertion didn't show up in the `wally` screenshot (905 bp and 4949 bp insertion)

**Comment by tobiasrausch** [comment]
Insertions are essentially point events on a linear reference so wally always visualizes them as a purple line. That's similar to IGV but apparently for large insertions, IGV switches to bigger blocks with the size information, which is not implemented in wally.

**Comment by baozg** [comment]
Got it! Thanks for the clarification, big insertions are really hard to present, since they disrupt the linear structure.

**Comment by baozg** [comment]
But I do see some numbers present or not. Even the number is enough for me to find complex regions in the genome. How did `wally` control for these number? By `-m`? By the way, what's the exact meaning of `-m`?
![Chr1_93793_93910](https://github.com/tobiasrausch/wally/assets/20680150/e203c2f3-d486-4af7-b0e9-9fcf5647a20e)

**Comment by tobiasrausch** [comment]
`-m` controls when abnormal paired-ends are visualized in red. It depends on the sharpness of the paired-end insert size distribution. The insertion length is plotted to the left of the insertion when you zoom into a small region. In other words, there needs to be enough space to plot the insertion length.

**Comment by baozg** [comment]
Thanks! I thought `-m` represent the variant size.
