### ISSUE TITLE
Show all supporting reads

### ISSUE THREAD

**Issue by jgarces02** [tobiasrausch/wally#8]
Hi @tobiasrausch, 

Wally is super straightforward to use, thanks! Quick question, please: is there any way of showing all supporting reads for an specific SV? Or at least, to increase the number of displayed reads (maybe collapsing them as IGV does).

For example, this should be an inversion (turquoise color) supported by three reads but I can only see two of them... ideally I'd like to see everything.

![image](https://github.com/tobiasrausch/wally/assets/27858969/1937008d-fcbe-4b2d-bac5-7893094daf05)

Thank you.

**Comment by tobiasrausch** [comment]
There is currently no squashed mode but you can increase the height of the plot to fit more reads.

`wally region -y 2048 ...`

**Comment by jgarces02** [comment]
Ok, thanks!
